# Generated by Django 2.2 on 2019-05-06 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clotheName', models.CharField(max_length=200)),
                ('clothePictureUrl', models.TextField()),
                ('clotheGender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('unisex', 'Unisex')], default='unisex', max_length=6)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='ClothesTest',
        ),
    ]
