# Generated by Django 2.2 on 2019-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0002_auto_20190506_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='clotheGender',
            field=models.CharField(choices=[('m', 'Man'), ('w', 'Woman'), ('u', 'Unisex')], default='unisex', max_length=6),
        ),
    ]
