# Generated by Django 2.2 on 2019-05-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0003_auto_20190506_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothesColorCode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patternName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='clothes',
            name='clotheGender',
            field=models.CharField(choices=[('m', 'Man'), ('w', 'Woman'), ('u', 'Unisex')], default='Unisex', max_length=6),
        ),
    ]
