# Generated by Django 2.2 on 2019-09-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0004_auto_20190525_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clothes',
        ),
    ]
