# Generated by Django 2.2 on 2019-09-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0005_delete_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clotheName', models.CharField(max_length=200)),
                ('clothePictureUrl', models.TextField()),
                ('clotheGender', models.CharField(choices=[('m', 'Man'), ('w', 'Woman'), ('u', 'Unisex')], default='Unisex', max_length=6)),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Category')),
            ],
        ),
    ]
