# Generated by Django 2.2 on 2019-09-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0007_remove_user_skincolorid'),
        ('DressManagement', '0006_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesForShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Clothes')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.Shape')),
            ],
        ),
    ]
