# Generated by Django 2.2 on 2019-09-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0007_clothesforshape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesForPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Clothes')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Place')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesForEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Clothes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Event')),
            ],
        ),
    ]
