# Generated by Django 2.2 on 2019-09-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0008_clothesforevent_clothesforplace_event_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='clotheDrescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='clotheLinkToBuy',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='clotheBrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Brand'),
            preserve_default=False,
        ),
    ]
