# Generated by Django 2.2 on 2019-10-25 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0009_auto_20190928_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='clotheBrand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.BrandOwner'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
