# Generated by Django 2.2 on 2019-10-25 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0010_auto_20191025_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='clotheBrand',
        ),
    ]
