# Generated by Django 2.2 on 2019-10-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0011_brandowner'),
        ('DressManagement', '0011_remove_clothes_clothebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='clotheBrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.BrandOwner'),
            preserve_default=False,
        ),
    ]
