# Generated by Django 2.2 on 2019-10-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0014_clothes_clothebrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='clotheBrand',
        ),
    ]
