# Generated by Django 2.2 on 2019-11-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0012_remove_brandowner_brandpicture'),
        ('DressManagement', '0016_clothes_clothebrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DressManagement.Clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.User')),
            ],
        ),
    ]
