# Generated by Django 2.2 on 2019-11-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DressManagement', '0017_favoriteclothes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteclothes',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
