# Generated by Django 2.2 on 2019-05-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shapeName', models.CharField(max_length=200)),
                ('shapeGender', models.CharField(choices=[('m', 'Man'), ('w', 'Woman')], max_length=6)),
                ('shapePictureUrl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkinColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinColorCode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(max_length=300)),
                ('userLastName', models.CharField(max_length=300)),
                ('userEmail', models.TextField()),
                ('userPictureUrl', models.TextField()),
                ('shapeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.Shape')),
                ('skinColorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.SkinColor')),
            ],
        ),
    ]
