# Generated by Django 2.2 on 2019-07-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
