# Generated by Django 2.2 on 2019-07-21 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbId', models.CharField(max_length=300)),
                ('userName', models.CharField(max_length=300)),
                ('userProfile', models.TextField()),
                ('userBodyPictureUrl', models.TextField()),
                ('userGender', models.CharField(max_length=10)),
                ('shapeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.Shape')),
                ('skinColorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ModuleUserInformation.SkinColor')),
            ],
        ),
    ]
