# Generated by Django 2.2 on 2019-08-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userBodyPictureUrl',
            field=models.TextField(blank=True),
        ),
    ]
