# Generated by Django 2.2 on 2019-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0004_auto_20190827_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='shape',
            name='shapeChest',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shape',
            name='shapeHip',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shape',
            name='shapeLeg',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shape',
            name='shapeShoulder',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shape',
            name='shapeWaist',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
