# Generated by Django 2.2 on 2019-09-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0005_auto_20190827_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='skincolor',
            name='skinColorName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
