# Generated by Django 2.2 on 2019-09-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0006_skincolor_skincolorname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skinColorId',
        ),
    ]
