# Generated by Django 2.2 on 2019-10-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0008_brandowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandowner',
            old_name='email',
            new_name='brandEmail',
        ),
        migrations.RenameField(
            model_name='brandowner',
            old_name='googleId',
            new_name='brandGoogleId',
        ),
    ]
