# Generated by Django 2.2 on 2019-10-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0009_auto_20191025_0636'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandOwner',
        ),
    ]
