# Generated by Django 2.2 on 2019-10-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0010_delete_brandowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.TextField()),
                ('brandGoogleId', models.TextField()),
                ('brandEmail', models.TextField()),
                ('brandPicture', models.TextField()),
            ],
        ),
    ]
