# Generated by Django 2.2 on 2019-10-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleUserInformation', '0011_brandowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandowner',
            name='brandPicture',
        ),
    ]
